# Makefile for Debian
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=/usr/share/arduino
include $(ARDMK_DIR)/Arduino.mk

# Makefile for ubuntu
# ARDUINO_DIR = /home/josef/arduino/arduino-1.8.10
# ARDMK_DIR = $(HOME)/.arduino_mk
# include $(ARDMK_DIR)/Arduino.mk
